### ISSUE TITLE
To give life to  structural testing environment.

### ISSUE THREAD

**Issue by ErikZA** [gabrielcostasilva/emater-mip-datacollection-app#87]
>>It consists of adding the necessary dependencies and creating the structure of folders that allow the execution of the unit tests.

**Comment by gabrielcostasilva** [comment]
Erik, você NÃO deve criar issues no MEU repositório. Crie um fork do repositório para você e controle as issues no SEU repositório. Quando terminar o projeto, fazemos um pull request.
