### ISSUE TITLE
To implement unit testing for pest management classes.

### ISSUE THREAD

**Issue by ErikZA** [gabrielcostasilva/emater-mip-datacollection-app#90]
> Consist of testing the MIPSampleService.java, PestDiseaseService.java, PestNaturalPredatorService.java, and PestService.java.

**Comment by gabrielcostasilva** [comment]
Erik, você NÃO deve criar issues no MEU repositório. Crie um fork do repositório para você e controle as issues no SEU repositório. Quando terminar o projeto, fazemos um pull request.
